import { visionApi } from '../config/visionApi';
import { ApiResponse } from '../types';
import {
  CreateFindingRequest,
  ExportFindingOptions,
  Finding,
  FindingExport
} from '../types/finding';

/**
 * Written analysis. The same endpoint an assistant writes through over MCP, so
 * what the app shows and what a later session reads back cannot drift.
 */
export const findingService = {
  async list(params: { project?: string; training?: string }): Promise<Finding[]> {
    const response = await visionApi.get('/findings', { params });
    return (response.data as ApiResponse<Finding[]>).data;
  },

  async create(request: CreateFindingRequest): Promise<Finding> {
    const response = await visionApi.post('/findings', request);
    return (response.data as ApiResponse<Finding>).data;
  },

  async remove(id: string): Promise<void> {
    await visionApi.delete(`/findings/${id}`);
  },

  /**
   * The finding as a LaTeX section.
   *
   * Generated by vision-service, not here: the results table is built from the
   * cited runs' recorded epochs, and the browser has neither the epochs nor any
   * business reformatting numbers on their way to a paper.
   */
  async exportLatex(id: string, options: ExportFindingOptions = {}): Promise<FindingExport> {
    const response = await visionApi.get(`/findings/${id}/latex`, { params: { ...options } });
    return (response.data as ApiResponse<FindingExport>).data;
  }
};
