services:
  vision-front:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${REGISTRY:-toomastahves}/vision-front:${TAG:-latest}
    restart: unless-stopped
    environment:
      VISION_API_URL: ${VISION_API_URL}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
      AUTH_FRONT_URL: ${AUTH_FRONT_URL}
      ACCOUNT_FRONT_URL: ${ACCOUNT_FRONT_URL}
      LABEL_FRONT_URL: ${LABEL_FRONT_URL}
    ports:
      - '3012:80'
    init: true
    networks:
      - visinnet

networks:
  visinnet:
    external: true
