services:
  landing-front:
    build:
      context: .
      dockerfile: Dockerfile
    image: toomastahves/landing-front:latest
    restart: unless-stopped
    environment:
      APP_URL: ${APP_URL}
    ports:
      - '3000:80'
    init: true
    networks:
      - visinnet

networks:
  visinnet:
    external: true
