services:
  landing-front:
    build:
      context: .
      dockerfile: Dockerfile
    image: toomastahves/landing-front:latest
    restart: unless-stopped
    environment:
      VISION_FRONT_URL: ${VISION_FRONT_URL}
      VISION_API_URL: ${VISION_API_URL}
    ports:
      - '3000:80'
    init: true
    networks:
      - visinnet

networks:
  visinnet:
    external: true
